name: Build MSP430 Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install MSP430-GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full srecord
          # Download the .7z archive
          wget https://dr-download.ti.com/software-development/ide-configuration-compiler-or-debugger/MD-LlCjWuAbzH/9.3.1.2/msp430-gcc-full-linux-x64-installer-9.3.1.2.7z
          # Extract the installer
          7z x msp430-gcc-full-linux-x64-installer-9.3.1.2.7z
          # Make the installer executable
          chmod +x msp430-gcc-full-linux-x64-installer-9.3.1.2.run
          sudo ./msp430-gcc-full-linux-x64-installer-9.3.1.2.run --mode unattended --prefix /opt/msp430-gcc

      - name: Add MSP430-GCC to PATH
        run: echo "/opt/msp430-gcc/bin" >> $GITHUB_PATH

      - name: Build Project
        run: make
